name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main  # Adjust if you use a different branch for deployment
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.7.3'  # Use your Node.js version

    - name: Install dependencies
      run: npm install
      working-directory: ./mission1backend  # Adjust to your backend directory

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        auth-type: 'SERVICE_PRINCIPAL'

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Mission1Backend'  # Replace with your Azure App Service name
        slot-name: 'production'
        package: ./mission1backend  # Adjust if necessary, generally the root of the repo
